trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: |
      wget -O qt-installer-noninteractive.qs https://pastebin.com/raw/nXrQLStE
      wget http://download.qt.io/official_releases/qt/5.11/5.11.3/qt-opensource-linux-x64-5.11.3.run
      chmod +x qt-opensource-linux-x64-5.11.3.run
      ./qt-opensource-linux-x64-5.11.3.run -platform minimal --script qt-installer-noninteractive.qs --verbose
    displayName: 'Install Qt 5.11.3'

  - script: |
      sudo apt-get -y update
      sudo apt-get -y install libfribidi-dev yasm nasm libvdpau1
      git clone https://github.com/mpv-player/mpv-build.git
      cd mpv-build
      ./use-mpv-release
      ./use-ffmpeg-release
      echo --enable-libmpv-shared > mpv_options
      ./rebuild -j2
      sudo ./install
      cd ../
    displayName: 'Install mpv'

  - script: |
      /home/vsts/Qt/5.11.3/gcc_64/bin/qmake
      make
      cp bin/* $(Build.ArtifactStagingDirectory)
    displayName: 'Build synchro'

  - task: CopyFiles@2
    inputs:
      sourceFolder: bin
      contents: '**'
      targetFolder: $(Build.ArtifactStagingDirectory)
    displayName: 'Copy build artifacts'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'Synchro-Linux64-$(Build.BuildNumber)'
    displayName: 'Publish build artifacts'

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:

  - powershell: |
      $ProgressPreference = 'SilentlyContinue'
      Invoke-WebRequest https://download.qt.io/official_releases/jom/jom.zip -OutFile $env:userprofile\jom.zip

      set-alias sz "$env:ProgramFiles\7-Zip\7z.exe"
      sz x $env:userprofile\jom.zip -y -o$env:userprofile
    displayName: 'Download jom'

  - script: |
      call "%programfiles(x86)%\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      git clone https://github.com/qt/qt5.git
      cd qt5
      git checkout tags/v5.11.3
      perl init-repository
    displayName: 'Download Qt'
    
  - script: |
      cd qt5
      call "%programfiles(x86)%\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      configure -prefix %userprofile%\Qt -platform win32-msvc -release -ltcg -nomake examples -nomake tools -nomake tests -opengl dynamic
      %userprofile%\jom /j 2 install
    displayName: "Build Qt"

  - powershell: |
      $ProgressPreference = 'SilentlyContinue'
      Invoke-WebRequest https://mpv.srsfckn.biz/mpv-dev-20181002.7z -OutFile mpv-dev-20181002.7z
      
      set-alias sz "$env:ProgramFiles\7-Zip\7z.exe"
      sz x mpv-dev-20181002.7z -y -ompv

      $oldfile = Get-Content mpv\x86_64\libmpv.def
      $newstuff = 'LIBRARY MPV-1`nEXPORTS`n`n'
      Set-Content mpv\x86_64\libmpv.def  -value $newstuff, $oldfile
    displayName: 'Download mpv lib'

  - script: |
      call "%programfiles(x86)%\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      lib /def:mpv\x86_64\libmpv.def /name:mpv\x86_64\mpv-1.dll /out:mpv\x86_64\libmpv.lib /MACHINE:X64
    displayName: 'Build mpv lib'
    
  - script: |
      call "%programfiles(x86)%\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      "%userprofile%\Qt\bin\qmake.exe"
      %userprofile%\jom /j 2
    displayName: 'Build synchro'

  - task: CopyFiles@2
    inputs:
      sourceFolder: bin
      contents: '**'
      targetFolder: $(Build.ArtifactStagingDirectory)
    displayName: 'Copy build artifacts'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'Synchro-Win64-$(Build.BuildNumber)'
    displayName: 'Publish build artifacts'