# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    sudo apt-get -y install p7zip-full
    wget https://git.kaidan.im/lnj/qli-installer/raw/master/qli-installer.py
    chmod +x qli-installer.py
    ./qli-installer.py 5.11.3 linux desktop
    ls
  displayName: 'Install Qt 5.11.3'

- script: |
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    sudo apt-get -y update
    sudo apt-get -y install mpv
  displayName: 'Install mpv'

- script: |
    5.11.3/gcc_64/bin/qmake
    make
    ls
  displayName: 'Build synchro'