# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    wget -O qt-installer-noninteractive.qs https://pastebin.com/raw/nXrQLStE
    wget http://download.qt.io/official_releases/qt/5.11/5.11.3/qt-opensource-linux-x64-5.11.3.run
    chmod +x qt-opensource-linux-x64-5.11.3.run
    ./qt-opensource-linux-x64-5.11.3.run -platform minimal --script qt-installer-noninteractive.qs --verbose
  displayName: 'Install Qt 5.11.3'

- script: |
    sudo apt-get -y update
    sudo apt-get -y install libfribidi-dev yasm nasm autoconf autotools-dev libx11-6 libxext6 libxinerama1 libxkbcommon0 libxrandr2 libxv1 libvdpau1 libgl1-mesa libjpeg8 
    git clone https://github.com/mpv-player/mpv-build.git
    cd mpv-build
    ./use-mpv-release
    ./use-ffmpeg-release
    echo --enable-libmpv-shared > mpv_options
    ./rebuild -j2
    sudo ./install
    cd ../
  displayName: 'Install mpv'

- script: |
    /home/vsts/Qt/5.11.3/gcc_64/bin/qmake
    make
    ls
  displayName: 'Build synchro'