# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    wget http://download.qt.io/official_releases/qt/5.12/5.12.2/qt-opensource-linux-x64-5.12.2.run
    chmod +x qt-opensource-linux-x64-5.12.2.run
    ./qt-opensource-linux-x64-5.12.2.run
  displayName: 'Install Qt5.12'

- script: |
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    sudo apt-get -y update
    sudo apt-get install mpv
  displayName: 'Install mpv'

- script: |
    qmake
    make
    ls
  displayName: 'Build synchro'