# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    wget -O qt-installer-noninteractive.qs https://pastebin.com/raw/nXrQLStE
    wget http://download.qt.io/official_releases/qt/5.11/5.11.3/qt-opensource-linux-x64-5.11.3.run
    chmod +x qt-opensource-linux-x64-5.11.3.run
    ./qt-opensource-linux-x64-5.11.3.run -platform minimal --script qt-installer-noninteractive.qs
    sudo find / -name 'qmake'
    ls
  displayName: 'Install Qt 5.11.3'

- script: |
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    sudo apt-get -y update
    sudo apt-get -y install mpv
  displayName: 'Install mpv'

- script: |
    qmake
    make
    ls
  displayName: 'Build synchro'