trigger:
- master

jobs:
- job: Windows
  timeoutInMinutes: 360
  pool:
    vmImage: 'vs2017-win2016'
  steps:

  - bash: yes "" | choco install jom nasm activeperl -y
    displayName: 'Download jom, nasm, and activeperl'

  - bash: |
      git clone https://github.com/openssl/openssl.git
      cd openssl
      git checkout tags/OpenSSL_1_1_0j
    displayName: 'Download OpenSSL'

  - script: |
      call "%programfiles(x86)%\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      set PATH=%programfiles%\NASM;%PATH%
      cd openssl
      C:\Perl64\bin\perl.exe Configure VC-WIN64A no-shared threads --prefix=%userprofile%\openssl64 --openssldir=%userprofile%\openssl64
      nmake
      nmake install
    displayName: 'Build OpenSSL'

  - powershell: |
      $ProgressPreference = 'SilentlyContinue'
      Invoke-WebRequest https://download.qt.io/archive/qt/5.11/5.11.3/single/qt-everywhere-src-5.11.3.tar.xz -OutFile qt-everywhere-src-5.11.3.tar.xz

      & "$env:ProgramFiles\7-Zip\7z.exe" x qt-everywhere-src-5.11.3.tar.xz -y
      & "$env:ProgramFiles\7-Zip\7z.exe" x qt-everywhere-src-5.11.3.tar -y
    displayName: 'Download Qt 5.11.3'
    
  - script: |
      call "%programfiles(x86)%\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      cd qt-everywhere-src-5.11.3
      configure -prefix .\ -platform win32-msvc -static -nomake examples -nomake tools -nomake tests -opengl dynamic -opensource -confirm-license -openssl-linked OPENSSL_LIBS="-llibssl -llibcrypto" -I %userprofile%\openssl64\include -L %userprofile%\openssl64\lib
    displayName: "Configure Qt 5.11.3"

  - script: |
      call "%programfiles(x86)%\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      cd qt-everywhere-src-5.11.3
      jom /j 2
    displayName: "Build Qt 5.11.3"
    failOnStderr: false

  - powershell: |
      $ProgressPreference = 'SilentlyContinue'
      Invoke-WebRequest https://mpv.srsfckn.biz/mpv-dev-20181002.7z -OutFile mpv-dev-20181002.7z
      
      & "$env:ProgramFiles\7-Zip\7z.exe" x mpv-dev-20181002.7z -y -ompv

      $oldfile = Get-Content mpv\x86_64\libmpv.def
      $newstuff = 'LIBRARY MPV-1`nEXPORTS`n`n'
      Set-Content mpv\x86_64\libmpv.def  -value $newstuff, $oldfile
    displayName: 'Download libmpv'

  - script: |
      call "%programfiles(x86)%\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      lib /def:mpv\x86_64\libmpv.def /name:mpv\x86_64\mpv-1.dll /out:mpv\x86_64\libmpv.lib /MACHINE:X64
    displayName: 'Build libmpv'
    
  - script: |
      call "%programfiles(x86)%\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      $(Build.Repository.LocalPath)\qt-everywhere-src-5.11.3\qtbase\bin\qmake.exe
      jom /j 2
    displayName: 'Build synchro'

  - task: CopyFiles@2
    inputs:
      sourceFolder: bin
      contents: '**'
      targetFolder: $(Build.ArtifactStagingDirectory)
    displayName: 'Copy build artifacts'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'Synchro-Win64-$(Build.BuildNumber)'
    displayName: 'Publish build artifacts'

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: brew install qt pkg-config mpv
    displayName: 'Install Qt and mpv'

  - script: |
      $(brew --prefix qt)/bin/qmake
      make
    displayName: 'Build synchro'

  - task: CopyFiles@2
    inputs:
      sourceFolder: bin
      contents: '**'
      targetFolder: $(Build.ArtifactStagingDirectory)
    displayName: 'Copy build artifacts'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'Synchro-macOS-$(Build.BuildNumber)'
    displayName: 'Publish build artifacts'

- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: |
      wget -O qt-installer-noninteractive.qs https://pastebin.com/raw/nXrQLStE
      wget http://download.qt.io/official_releases/qt/5.9/5.9.2/qt-opensource-linux-x64-5.9.2.run
      chmod +x qt-opensource-linux-x64-5.9.2.run
      ./qt-opensource-linux-x64-5.9.2.run -platform minimal --script qt-installer-noninteractive.qs --verbose
    displayName: 'Install Qt 5.9.2'

  - script: |
      sudo apt-get -y update
      sudo apt-get -y install libfribidi-dev yasm nasm libvdpau1
      git clone https://github.com/mpv-player/mpv-build.git
      cd mpv-build
      ./use-mpv-release
      ./use-ffmpeg-release
      echo --enable-libmpv-shared > mpv_options
      ./rebuild -j2
      sudo ./install
      cd ../
    displayName: 'Install mpv'

  - script: |
      /home/vsts/Qt/5.9.2/gcc_64/bin/qmake
      make
    displayName: 'Build synchro'

  - task: CopyFiles@2
    inputs:
      sourceFolder: bin
      contents: '**'
      targetFolder: $(Build.ArtifactStagingDirectory)
    displayName: 'Copy build artifacts'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'Synchro-Linux64-$(Build.BuildNumber)'
    displayName: 'Publish build artifacts'
